alter table LAZORENKO_AL.specialisation modify enter_into_the_sys default sysdate;
alter table LAZORENKO_AL.hospital modify enter_into_the_sys default sysdate;

drop table LAZORENKO_AL.mon_fri_open;
drop table LAZORENKO_AL.mon_fri_close;
drop table LAZORENKO_AL.sat_sun_open;
drop table LAZORENKO_AL.sat_sun_close;
drop table LAZORENKO_AL.work_time;

create table LAZORENKO_AL.work_time (
    work_time_id number generated by default as identity
    (start with 1 maxvalue 999999999999999 minvalue 1 nocycle nocache noorder) primary key,
    day number,
    begin_time varchar2(100) null,
    end_time varchar2(100) null,
    hospital_id number references LAZORENKO_AL.hospital(hospital_id) not null
);

insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '16:00', 4);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, null, null, 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, null, null, 5);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '8:00', '18:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '8:00', '18:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '8:00', '18:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '8:00', '18:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '8:00', '18:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '9:00', '16:00', 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, null, null, 6);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '16:00', 7);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, null, null, 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, null, null, 8);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '16:00', 9);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '8:00', '17:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '8:00', '17:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '8:00', '17:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '8:00', '17:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '8:00', '17:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '9:00', '16:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '15:00', 10);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '20:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '20:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '20:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '20:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '20:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '15:00', 11);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '7:00', '18:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '7:00', '18:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '7:00', '18:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '7:00', '18:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '7:00', '18:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, null, null, 12);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '18:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '18:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '18:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '18:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '18:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '16:00', 13);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(1, '9:00', '20:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(2, '9:00', '20:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(3, '9:00', '20:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(4, '9:00', '20:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(5, '9:00', '20:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(6, '10:00', '17:00', 14);
insert into LAZORENKO_AL.work_time(day, begin_time, end_time, hospital_id)
values(7, '10:00', '15:00', 14);

alter table LAZORENKO_AL.hospital drop column work_time_id;

drop table LAZORENKO_AL.ages;

update LAZORENKO_AL.age_groups set age_groups.min_age = 0, age_groups.max_age = 2
WHERE age_groups.age_group_id=1;
update LAZORENKO_AL.age_groups set age_groups.min_age=3, age_groups.max_age=17
WHERE age_groups.age_group_id=2;
update LAZORENKO_AL.age_groups set age_groups.min_age=18, age_groups.max_age=59
WHERE age_groups.age_group_id=3;
update LAZORENKO_AL.age_groups set age_groups.min_age=60, age_groups.max_age=100
WHERE age_groups.age_group_id=4;