create table LAZORENKO_AL.work_time (
    work_time_id number generated by default as identity
    (start with 1 maxvalue 999999999999999 minvalue 1 nocycle nocache noorder) primary key,
    day varchar2(100),
    begin_time varchar2(100),
    end_time varchar2(100),
    hospital_id number references LAZORENKO_AL.hospital(hospital_id) not null
);